name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * */2'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - x86
    container:
      image: ghcr.io/jhnc-oss/yocto-image/yocto:34
      options: --user root
    name: "Build (${{ matrix.arch }})"
    steps:
      - uses: actions/checkout@main
      - name: Synchronize Repositories
        run: |
          PATH="${HOME}/.local/bin:${PATH}"
          repo init -u https://github.com/jhnc-oss/yocto-manifests.git -b MS18
          repo sync
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto
      - name: Build
        run: |
          export YOCTO_TARGET_ARCH=${{ matrix.arch }}
          export BB_ENV_EXTRAWHITE=YOCTO_TARGET_ARCH
          export TEMPLATECONF=/opt/yocto/protos/conf/templates
          source poky/oe-init-build-env
          bitbake-layers show-layers
          bitbake -p zlib
          if [[ ${{ github.event_name }} == 'schedule' ]]; then
            bitbake -n world
          fi
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto
