name: ci

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jhnc-oss/yocto-image/yocto:latest
      options: --user root
    name: "Build"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
      - name: Synchronize Repositories
        run: |
          repo init -u git://github.com/jhnc-oss/yocto-manifests.git -b dunfell-23.0.10
          repo sync
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto
      - name: Build
        run: |
          source poky/oe-init-build-env
          bitbake -p zlib
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto

