name: ci

on:
  push:
  pull_request:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - x86
    container:
      image: ghcr.io/jhnc-oss/yocto-image/yocto:latest
      options: --user root
    name: "Build (${{ matrix.arch }})"
    steps:
      - uses: actions/checkout@main
      - name: Setup
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pip install -r requirements.txt
      - name: Synchronize Repositories
        run: |
          repo init -u https://github.com/jhnc-oss/yocto-manifests.git -b dunfell-23.0.11
          repo sync
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto
      - name: Build
        env:
          YOCTO_TARGET_ARCH: ${{ matrix.arch }}
        run: |
          TEMPLATECONF=/opt/yocto/meta-protos/conf/templates source poky/oe-init-build-env
          bitbake -p zlib
        shell: sudo -u yocto bash --noprofile --norc -eo pipefail {0}
        working-directory: /opt/yocto

